### PR TITLE
UserRoleResponseDto mapping improved: added email mapping

### PR DESCRIPTION
**Pull request by bestDvlpr**
UserRoleResponseDto mapping corrected: email is mapped from source's user member

### CODE REVIEW

**Comment by bestDvlpr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bestDvlpr** [comment]
recheckcla

**Comment by bestDvlpr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bestDvlpr** [comment]
recheckcla

**Review by pospielov — APPROVED** [review]

**Pull request merged**
