### PR TITLE
Update docker image, fix GPU vision & Deps to python 3.11

### PR DESCRIPTION
**Pull request by jack60612**

### CODE REVIEW

**Comment by jack60612** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jack60612** [comment]
recheckcla

**Comment by pospielov** [comment]
Hi, thanks for your contribution. 
It doesn't make sense to use tensorflow image and then install mxnet.
So this fix makes sense only for the default FaceNet build.
As for mxnet it looks like it doesn't support cuda 11.8, so it won't work at all.
This is why we are researching how to migrate to another library from mxnet.

**Comment by jack60612** [comment]
> Hi, thanks for your contribution. It doesn't make sense to use tensorflow image and then install mxnet. So this fix makes sense only for the default FaceNet build. As for mxnet it looks like it doesn't support cuda 11.8, so it won't work at all. This is why we are researching how to migrate to another library from mxnet.

I think i can change it back to the nvidia image tbh, it just makes it install faster.

**Comment by jack60612** [comment]
> I passed this pull request to our developer who researches this problem, but he is on vacation now

ok, sounds good.

**Comment by jack60612** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/exadel-inc/CompreFace/blob/master/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> You can retrigger this bot by commenting **recheckcla** in this Pull Request

I have read the CLA Document and I hereby sign the CLA

**Comment by Anatolii-R** [comment]
> Mxnet works for me(cuda 11.8), I was using arcface gpu + this image and kube

Hi Jack
I can see that the CPU build is working, but I'm curious about how you managed to incorporate CUDA 11.8 into the GPU build. Would you be able to share some insights on that?

**Comment by Anatolii-R** [comment]
I'm encountering an error while attempting to build code for use with a GPU.
Screenshot 2023-04-24 at 17 12 11

**Comment by jack60612** [comment]
That should be solved by the changes in dependency.py

**Pull request closed without merging**
