### PR TITLE
Added pluginsVersions into FaceVerification

### PR DESCRIPTION
**Pull request by stormtronec**

### CODE REVIEW

**Review by pospielov — DISMISSED** [review]

**Comment by sshimanski** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sshimanski** [comment]
recheckcla

**Comment by sshimanski-exadel** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sshimanski-exadel** [comment]
recheckcla

**Review by pospielov — APPROVED** [review]

**Pull request merged**
