### PR TITLE
[solve]  Focus input when creating new Service and new Application

### PR DESCRIPTION
**Pull request by durgeshmeena**
solved Issue #614  
ezgif com-gif-maker

### CODE REVIEW

**Comment by durgeshmeena** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by durgeshmeena** [comment]
recheckcla

**Review by pospielov — CHANGES_REQUESTED** [review]
I added comments, focus on input doesn't work.
Also, I see that you fixed another issue in this pull request.
I'm OK to merge them together, but I suggest splitting the fixes on different pull requests, because:
1. If you participate in Hacktoberfest, they count pull requests, not the fixed issues
2. Issue with tooltips is ready to be merged, but with focus not. If you split the pull request I would be able to merge at least one issue for now.

**Comment by pospielov** [comment]
Also, please write a comment here:
https://github.com/exadel-inc/CompreFace/issues/615
So I will be able to assign the issue to you

**Comment by pospielov** [comment]
I checked the functionality in both pull requests - everything works as expected. 
But I can't merge it.
Both pull requests contain "removing" commits. So if I merge both of them - it will firstly add and then remove both features. This is how git works.
There are three options how to handle this:
1. Create new branches from the master and change the code manually. Create new pull requests
2. Create new branches from master and cherry-pick the proper commits. Create new pull requests
3. You can do a git hard reset operation, but I do not recommend it as this is a dangerous way.

**Pull request closed without merging**
